name: upon
version: '0.1.0.0'
category: Web
author: Ignat Insarov
maintainer: kindaro@gmail.com
copyright: 2017 Ignat Insarov
license: ISC
github: kindaro/upon
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Control.Monad.State.Upon
  dependencies:
  - base >=4.7 && <5
  - mtl
tests:
  upon-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - upon
    - HTF
    - mtl
